### ISSUE TITLE
Vídeo da apresentação

### ISSUE THREAD

**Issue by DanielPortods** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#13]
## Descrição
Issue voltada para a produção do vídeo da apresentação referente a entrega 1.

## Tarefas
- [x] Reunir os integrantes para realização da apresentação;
- [x] Disponibilizar o vídeo na wiki;
- [x] Realizar a entrega.

## Critérios de Aceitação
- [x] A entrega estar feita e o vídeo disponível na wiki.

**Comment by sergiosacj** [comment]
Edição finalizada e vídeo disponível como não-listado no youtube

https://youtu.be/amFfvNnYnuI

**Comment by estevaoreis25** [comment]
Novo link do vídeo;

https://youtu.be/n_HoFJHQjDU
