### ISSUE TITLE
Desenvolver a Rich Picture

### ISSUE THREAD

**Issue by DanielPortods** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#2]
## Descrição
Issue direcionada ao desenvolvimento da Rich Picture. Partindo do diagrama já desenvolvido, os integrantes podem fazer o seu modelo de acordo com o que for discutido nessa issue. Ao final o responsável pela tarefa terá de disponibilizar um diagrama vetorizado na wiki.

## Tarefas
- [x] Disponibilizar o diagrama de partida;
- [x] Realizar correções no diagrama de partida;
- [x] Disponibilizar o diagrama final geral;
- [x] Preencher a página do artefato na wiki.

## Critérios de Aceitação
- [x] A versão final geral estar pronta e disponível na issue;
- [x] A página da wiki estar completa e devidamente revisada.

**Comment by DanielPortods** [comment]
## Diagrama de partida:
![Rich Picture de partida](https://user-images.githubusercontent.com/48573556/107884441-e7bcd880-6ed3-11eb-878e-ada2658bbfbd.png)

**Comment by sergiosacj** [comment]
## Rich Picture Completa da Aplicação

![rich_picture_CDT](https://user-images.githubusercontent.com/36544528/107885166-797a1500-6ed7-11eb-82b3-48506c54ce82.jpg)

**Comment by emysdias** [comment]
![photo4997193744977602793](https://user-images.githubusercontent.com/52640974/107980018-52d2e180-6f9e-11eb-8a62-d3bb8821a278.jpg)

**Comment by DanielPortods** [comment]
Tentei corrigir allguns pontos de acordo com os padrões de rech pictue.
Aproveito para sugerir esse escopo com três contextos: funcionalidades principais, dados pessoais e informações.
![rp](https://user-images.githubusercontent.com/48573556/108099677-b246f500-7063-11eb-8f0d-82cdfadbcf22.jpg)

**Comment by emysdias** [comment]
> Tentei corrigir allguns pontos de acordo com os padrões de rech pictue.
> Aproveito para sugerir esse escopo com três contextos: funcionalidades principais, dados pessoais e informações.
> ![rp](https://user-images.githubusercontent.com/48573556/108099677-b246f500-7063-11eb-8f0d-82cdfadbcf22.jpg)

ficou bonzão

**Comment by DanielPortods** [comment]
## Funcionalidades Principais
![rpFuncPrincipais](https://user-images.githubusercontent.com/48573556/108143785-1e971800-70a7-11eb-9c19-3271177b1341.png)

**Comment by DanielPortods** [comment]
## Informações
![rpInformacoes](https://user-images.githubusercontent.com/48573556/108143861-44242180-70a7-11eb-9931-1fbae7790712.png)

**Comment by DanielPortods** [comment]
## Informações do Usuário
![rpInfoUsuario](https://user-images.githubusercontent.com/48573556/108143910-5d2cd280-70a7-11eb-87c1-a9c9fa404ba7.png)
