### ISSUE TITLE
Gravar a apresentação e finalizar a entrega 2

### ISSUE THREAD

**Issue by DanielPortods** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#32]
## Descrição
Issue direcionada para a gravação do video de apresentação, publicação na wiki e finalização da entrega.

## Tarefas
- [x] Marcar o dia de realização do vídeo;
- [x] Gravar o vídeo de apresentação;
- [x] Se necessário, editar o vídeo;
- [x] Publicar a apresentação e disponibilizar na Wiki;
- [x] Finalizar a entrega no Moodle.

## Critérios de Aceitação
- [x] Vídeo estar disponível na Wiki;
- [x] A entrega está terminada no Moodle.

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/110828767-25641580-8276-11eb-9a25-94a59426ac86.png)
