### ISSUE TITLE
Horários da equipe

### ISSUE THREAD

**Issue by emysdias** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#4]
## Descrição
Essa issue vai ser responsável em colocar todos os horários em que a equipe está ocupada, ou livre para ter um controle melhor de como vai ficar organizado nossas reuniões ou algo que precise.

## Tarefas
- [x] Colocar os horários do time em alguma planilha para uma visualização melhor.

## Critérios de Aceitação
- [x] A tabela estar certa com os horários do time.

**Comment by enzoggqs** [comment]
Os horários foram criados com uma tabela no excel, segue o [link](https://unbbr-my.sharepoint.com/:x:/g/personal/160119006_aluno_unb_br/EUwWZKXQLa1Am4fnvjz6UKgBVQ6pZN1kQs6erOVDQZiVZQ?e=XgQ5gN).

**Comment by DanielPortods** [comment]
Falta:
- [ ] Disponibilizar os Horários da equipe na wiki.
