### ISSUE TITLE
Ferramentas utilizadas

### ISSUE THREAD

**Issue by emysdias** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#5]
## Descrição
Colocar quais ferramentas que serão utlizadas durante todo o semestre na matéria de Requisitos.

## Tarefas
- [x] Adicionar ferramentas que foram e que serão utilizadas durante o curso de Requisitos.

## Critérios de Aceitação
- [x] Ter todas as ferramentas da maneira correta.

**Comment by DanielPortods** [comment]
Falta: 
- [ ] Disponibilizar a lista de ferramentas na wiki.

**Comment by sergiosacj** [comment]
> Falta:
> 
> * [x]  Disponibilizar a lista de ferramentas na wiki.

Reabrindo essa issue até o PR linkado ser aceito!
