### ISSUE TITLE
Reunião 23/03/2021

### ISSUE THREAD

**Issue by enzoggqs** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#54]
## Descrição

Issue direcionada para a realização e registro da reunião de planejamento do dia 23/03/2021

## Tarefas
- [ ] Marcar a reunião;
- [ ] Realizar a reunião;
- [ ] Dividir tarefas;
- [ ] Definir responsáveis por cada tarefa e seus revisores;
- [ ] Fazer a ata.

## Critérios de Aceitação
- [ ] Tarefas realizadas;
- [ ] Ata publicada

**Comment by enzoggqs** [comment]
Issue clonada

**Comment by sergiosacj** [comment]
A issue mais [antiga](https://github.com/Requisitos-de-Software/2020.2-CarteiraDigitalTransito/issues/52#issue-838643206) vai ser usada.
