### ISSUE TITLE
Introdução da página de planejamento

### ISSUE THREAD

**Issue by emysdias** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#6]
## Descrição
Fazer um texto explicando sobre o planejamento decidido pela equipe.

## Tarefas
- [x] Colocar a introdução na página onde fica o planejamento do time.

## Critérios de Aceitação
- [x] A introdução estar na página correta.

**Comment by sergiosacj** [comment]
Como descrito no PR linkado, essa issue já foi resolvida e pode ser fechada.
