### ISSUE TITLE
Fazer a Wiki do projeto

### ISSUE THREAD

**Issue by emysdias** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#7]
## Descrição
Aqui será feito a estruturação do Github Pages, juntamente com a Home.

## Tarefas
- [x] Ter a wiki estruturada.
- [x] Fazer a home da wiki

## Critérios de Aceitação
- [x] As tarefas serem feitas corretamente.

**Comment by sergiosacj** [comment]
Como descrito no PR linkado, essa issue já foi resolvida e pode ser fechada.
