### ISSUE TITLE
Metodologia do projeto

### ISSUE THREAD

**Issue by emysdias** [Requisitos-de-Software/2020.2-CarteiraDigitalTransito#8]
## Descrição
Desenvolver qual será a metodologia que será usada no projeto durante o semestre.

## Tarefas
- [x] Apresentar a metodologia pensada.
- [x] Colocar a metodologia na Wiki

## Critérios de Aceitação
- [x] Todos da equipe aprovarem a metodologia.

**Comment by DanielPortods** [comment]
A métodologia já está disponível na wiki e foi anteriormente aceita por todos integrante no nosso canal de comunição do Telegram.
